// Константы для определения действий
export const MODAL_FETCH_ERRORED = 'MODAL_FETCH_ERRORED'; // Ошибка загрузки данных для модального окна
export const MODAL_START_LOADING = 'MODAL_START_LOADING'; // Начало загрузки данных для модального окна
export const MODAL_IS_OPEN = 'MODAL_IS_OPEN'; // Открыть модальное окно
export const MODAL_FETCH_DATA_SUCCESS = 'MODAL_FETCH_DATA_SUCCESS'; // Данные для модального окна успешно загружены
export const INFO_SPEC_KEY = 'INFO_SPEC_KEY'; // Блок спецификации в секции информации
export const INFO_LEGEND_KEY = 'INFO_LEGEND_KEY'; // Блок легенды в секции информации
export const LAYER_SHOW_CHECKED = 'LAYER_SHOW_CHECKED'; //Изменение статуса слоя(выбран или нет)
export const LAYER_FIND_STANTION = 'LAYER_FIND_STANTION'; //Найти станцию по коду
export const LAYER_REFRESH = 'LAYER_REFRESH'; // Обновить слой
export const LAYER_RESET_ZOOM = 'LAYER_RESET_ZOOM'; // Сброс маштабирования
export const NAVBAR_FETCH_ERRORED = 'NAVBAR_FETCH_ERRORED'; // Ошибка загрузки меню (кропки в левом блоке)
export const NAVBAR_FETCH_DATA_SUCCESS = 'NAVBAR_FETCH_DATA_SUCCESS'; // Успешная загрузка меню
export const NAVBAR_START_LOADING = 'NAVBAR_START_LOADING'; // Начало загрузки меню
export const LOADER_START_SHOW = 'LOADER_START_SHOW'; // ?
export const LOADER_STOP_SHOW = 'LOADER_STOP_SHOW'; // ?
export const FORECAST_FETCH_ERRORED = 'FORECAST_FETCH_ERRORED'; //Ошибка загрузки данных о погоде в секции информации
export const FORECAST_START_LOADING = 'FORECAST_START_LOADING'; //начало загрузки данных о погоде
export const FORECAST_CLOSE = 'FORECAST_CLOSE'; // Убрать окно с погодой из секции информации(при показе основной карты)
export const FORECAST_OPEN = 'FORECAST_OPEN'; // Показать окно с погодой (при показе карты региона)
export const FORECAST_FETCH_DATA_SUCCESS = 'FORECAST_FETCH_DATA_SUCCESS'; //Успешная загрузка данных по погоде
export const STORM_START_LOADING = 'STORM_START_LOADING'; // Начало загрузки данных по штормовым пред.
export const STORM_FETCH_ERRORED = 'STORM_FETCH_ERRORED'; // Ошибка загрузки данных по штормовым пред.
export const STORM_REGION_FETCH_SUCCESS = 'STORM_REGION_FETCH_SUCCESS'; //Данные штормовых предупреждений по региону
export const STORM_ALL_FETCH_SUCCESS = 'STORM_ALL_FETCH_SUCCESS'; // Данные штормовых предупреждений по дороге
export const STORM_REGION_UPDATE_SUCCESS = 'STORM_REGION_UPDATE_SUCCESS'; // Обновление данных штормовых предупреждений по региону
export const STORM_ALL_UPDATE_SUCCESS = 'STORM_ALL_UPDATE_SUCCESS'; // Обновление данных штормовых предупреждений по дороге
export const TABLO_TOGGLE_MAIN_MAP = 'TABLO_TOGGLE_MAIN_MAP'; //Переключение карты табло
export const TABLO_FETCH_SUCCESS = 'TABLO_FETCH_SUCCESS'; //Загрузка данных о предприятиях в табло
export const TABLO_FETCH_ERROR = 'TABLO_FETCH_ERROR'; // Ошибка загрузки данных о предприятиях в табло
export const TABLO_START_LOADING = 'TABLO_START_LOADING'; //Начало загрузки данных о предприятиях в табло
export const WEATHER_FETCH_SUCCESS = 'WEATHER_FETCH_SUCCESS'; //Данные по фактической погоде
export const WEATHER_FETCH_ERROR = 'WEATHER_FETCH_ERROR'; // Ошибка загрузки данных о фактической погоде
export const WEATHER_START_LOADING = 'WEATHER_START_LOADING'; //Начало загрузки данных о фактической погоде
export const WEATHER_WIN_OPEN = 'WEATHER_WIN_OPEN'; //Показать окно по фактической погоде
export const WEATHER_WIN_CLOSE = 'WEATHER_WIN_CLOSE'; //Закрыть окно по фактической погоде
export const SNOW_TECH_FETCH_ERROR = 'SNOW_TECH_FETCH_ERROR'; //Ошибка загрузки данных по снегоуборочной технике
export const SNOW_TECH_FETCH_SUCCESS = 'SNOW_TECH_FETCH_SUCCESS'; //Данные по снегоуборочной технике
export const SNOW_TECH_START_LOADING = 'SNOW_TECH_START_LOADING'; //Начало загрузки данных по снегоуборочной технике
export const PIPE_FETCH_ERROR = 'PIPE_FETCH_ERROR'; //Ошибка загрузки данных по трубам
export const PIPE_FETCH_SUCCESS = 'PIPE_FETCH_SUCCESS'; //Данные по трубам
export const PIPE_START_LOADING = 'PIPE_START_LOADING'; //Начало загрузки данных по трубам
export const SPEC_TECH_FETCH_ERROR = 'SPEC_TECH_FETCH_ERROR'; //Ошибка загрузки данных по спецтехнике
export const SPEC_TECH_FETCH_SUCCESS = 'SPEC_TECH_FETCH_SUCCESS'; //Данные по спецтехнике
export const SPEC_TECH_START_LOADING = 'SPEC_TECH_START_LOADING'; //Начало загрузки данных по спецтехнике
export const GPS_FETCH_ERROR = 'GPS_FETCH_ERROR'; //Ошибка загрузки данных для GPS
export const GPS_FETCH_SUCCESS = 'GPS_FETCH_SUCCESS'; //Данные для GPS
export const GPS_START_LOADING = 'GPS_START_LOADING'; //Начало загрузки данных для GPS
export const GPS_RESET_CODE = 'GPS_RESET_CODE'; //Сброс GPS
export const DNC_FETCH_ERROR = 'DNC_FETCH_ERROR'; //Ошибка загрузки данных для слоя диспечерских участков
export const DNC_FETCH_SUCCESS = 'DNC_FETCH_SUCCESS'; //Данные для слоя диспечерских участков
export const DNC_START_LOADING = 'DNC_START_LOADING'; //Начало загрузки данных для слоя диспечерских участков
export const VCHD_FETCH_ERROR = 'VCHD_FETCH_ERROR'; //Ошибка загрузки данных слоя ВЧД
export const VCHD_FETCH_SUCCESS = 'VCHD_FETCH_SUCCESS'; //Данные слоя ВЧД
export const VCHD_START_LOADING = 'VCHD_START_LOADING'; //Начало загрузки данных слоя ВЧД
export const STOK_FETCH_ERROR = 'STOK_FETCH_ERROR'; //Ошибка загрузки данных для слоя очистных сооружений
export const STOK_FETCH_SUCCESS = 'STOK_FETCH_SUCCESS'; //Данные для слоя очистных сооружений
export const STOK_START_LOADING = 'STOK_START_LOADING'; //Начало загрузки данных для слоя очистных сооружений
export const RISKOBJ_FETCH_ERROR = 'RISKOBJ_FETCH_ERROR'; //Ошибка загрузки данных для слоя ОНЭУ
export const RISKOBJ_FETCH_SUCCESS = 'RISKOBJ_FETCH_SUCCESS'; //Данные для слоя ОНЭУ
export const RISKOBJ_START_LOADING = 'RISKOBJ_START_LOADING'; //Начало загрузки данных для слоя ОНЭУ
export const ABANDONED_START_LOADING = 'ABANDONED_START_LOADING'; //Ошибка загрузки данных по брошенным поездам
export const ABANDONED_FETCH_ERROR = 'ABANDONED_FETCH_ERROR'; //Начало загрузки данных по брошенным поездам
export const ABANDONED_FETCH_SUCCESS = 'ABANDONED_FETCH_SUCCESS'; //Данные по брошенным поездам
