export const layersInit = [
  {
    layer: "pch",
    show: false,
    name: "Границы ПЧ",
    visible: "visible",
    disabled: false,
    id: 0,
  },
  {
    layer: "shch",
    show: false,
    name: "Границы ШЧ",
    visible: "visible",
    disabled: false,
    id: 1,
  },
  {
    layer: "vchd",
    show: false,
    name: "Границы ВЧД",
    visible: "visible",
    disabled: false,
    id: 2,
  },
  {
    layer: "ech",
    show: false,
    name: "Границы ЭЧ",
    visible: "visible",
    disabled: false,
    id: 3,
  },
  {
    layer: "dnc",
    show: false,
    name: "Диспетчерские участки",
    visible: "visible",
    disabled: false,
    id: 4,
  },
  {
    layer: "current",
    show: false,
    name: "Электрификация",
    visible: "visible",
    disabled: false,
    id: 5,
  },

  {
    layer: "loco dolb",
    show: false,
    name: "Локомотивные плечи",
    visible: "visible",
    disabled: false,
    id: 6,
  },
  {
    layer: "loco_team",
    show: false,
    name: '"Плечи" локомотивных бригад',
    visible: "visible",
    disabled: false,
    id: 7,
  },
  {
    layer: "spec_trains",
    show: false,
    name: "Восстановительные и пожарные поезда",
    visible: "visible",
    disabled: false,
    id: 8,
  },
  {
    layer: "dtv",
    show: false,
    name: "ДТВУ",
    visible: "visible",
    disabled: false,
    id: 9,
  },

  {
    layer: "ngch",
    show: false,
    name: "НГЧ, дистанция гражданских сооружений",
    visible: "visible",
    disabled: false,
    id: 10,
  },
  {
    layer: "trains_distantions",
    show: true,
    name: "Штормовое пердупреждение",
    visible: "visible",
    disabled: false,
    id: 11,
  },
];
